<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Checkout_icon_search</name>
   <tag></tag>
   <elementGuidId>aeb6c3e8-2b11-4add-b7d3-8fa3a528b661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noo-site']/header/div[2]/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cc57f1d1-9478-401c-ac9e-ffdbee8d86a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_search</value>
      <webElementGuid>0d6888a4-56c5-4e9f-9dca-7c1552e69b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/header[@class=&quot;noo-header fixed_top header-3 header-eff&quot;]/div[@class=&quot;navbar-wrapper&quot;]/div[@class=&quot;navbar navbar-default&quot;]/a[@class=&quot;noo-search&quot;]/i[@class=&quot;icon_search&quot;]</value>
      <webElementGuid>607c6c85-8254-4135-adcc-ac7ba5d6d34e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/header/div[2]/div/a/i</value>
      <webElementGuid>aadec42d-c6b0-4825-97a5-dd55c3147070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>162862d3-185d-43ae-a269-4e737282e53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
